name: marquee
description: "⏩ A Flutter widget that scrolls text infinitely. Provides many
  customizations including custom scroll directions, durations, curves as well
  as pauses after every round."
version: 1.7.0
homepage: https://github.com/marcelgarus/marquee
issue_tracker: https://github.com/marcelgarus/marquee/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fading_edge_scrollview: ^3.0.0
  flutter_widget_from_html:

dev_dependencies:
  flutter_test:
    sdk: flutter
